#!/bin/bash

profile=$1
account_id=$(aws configure get sso_account_id --profile $profile)
role=$(aws configure get sso_role_name --profile $profile)
key=$(aws configure get aws_secret_access_key --profile $profile)
key_id=$(aws configure get aws_access_key_id --profile $profile)
token=$(aws configure get aws_session_token --profile $profile)

aws configure set sso_account_id $account_id --profile default
aws configure set sso_role_name $role --profile default
aws configure set aws_secret_access_key $role --profile default
aws configure set aws_access_key_id $key_id --profile default
aws configure set aws_session_token $token --profile default
