#!/bin/bash

export AWS_PROFILE=$1

function get_access_token_from_cache {
  grep -l accessToken ~/.aws/sso/cache/* |
    xargs jq -r ".accessToken"
}

REGION=$(aws configure get sso_region --profile $1)
ACCOUNT_ID=$(aws configure get sso_account_id --profile $1)
ROLE_NAME=$(aws configure get sso_role_name --profile $1)

if [ -d ~/.aws/sso/cache ]; then
  ACCESS_TOKEN=$(get_access_token_from_cache)
fi

cred=$(aws sso get-role-credentials \
  --account-id ${ACCOUNT_ID} \
  --role-name ${ROLE_NAME} \
  --access-token ${ACCESS_TOKEN} \
  --region ${REGION} \
  --query roleCredentials)

if [ $? -ne 0 ]; then
  aws sso login
  ACCESS_TOKEN=$(get_access_token_from_cache)

  cred=$(aws sso get-role-credentials \
    --account-id ${ACCOUNT_ID} \
    --role-name ${ROLE_NAME} \
    --access-token ${ACCESS_TOKEN} \
    --region ${REGION} \
    --query roleCredentials)
fi

aws configure set aws_secret_access_key $(echo ${cred} | jq -r '.secretAccessKey') --profile $1
aws configure set aws_access_key_id $(echo ${cred} | jq -r '.accessKeyId') --profile $1
aws configure set aws_session_token $(echo ${cred} | jq -r '.sessionToken') --profile $1
