#!/bin/bash

desired_count=$1

if [ -z "${desired_count}"  ]; then
  read -p 'desired-task-count?: ' desired_count
fi

aws ecs list-clusters |
  jq -r '.clusterArns[]' |
  awk -F '/' '{ print $2 }' |
  fzf -m --select-1 |
  while read cluster; do
    aws ecs list-services --cluster "${cluster}" |
      jq -r '.serviceArns[]' |
      fzf -m --select-1 |
      xargs -n1 -I{} aws ecs update-service --cluster "${cluster}" --service {} --desired-count "${desired_count}" --force-new-deployment
  done
