#!/bin/bash

while getopts "r" OPT; do
  case $OPT in
    r)
      recursive_options='-r --exclude=".git" --exclude=".terraform"'
      ;;
  esac
  shift
done

delta_options=${@:3:$(($# - 1))}

diff -u ${recursive_options} $1 $2 | delta $delta_options
